### PR TITLE
added jamovi-current (latest jamovi)

### PR DESCRIPTION
**Pull request by Gootjes**
Let me know if I did anything wrong, this is my first package.

### CODE REVIEW

**Comment by OlafHaag** [comment]
Hey @Gootjes , thanks for reaching out. It seems you created a separate new package for the pre-release versions of jamovi? To create separate packages for that is discouraged by chocolatey. We should add pre-release versions to the jamovi packages that are already there, but make it explicit in the versioning of the package, that it is a pre-release. If done right, chocolatey will pick up on that and for people preferring to use the latest stable version, chocolatey will not update to the dev versions, unless you make it explicit.

**Comment by Gootjes** [comment]
@OlafHaag Thanks for the feedback!
To solve it, I implemented streams: the script appends `-current` to the current (pre-release) version of jamovi. Consequently, users now have to specify `--pre` to get the latest (pre-release, beta, current, or however you want to call it) version. Chocolatey should then automatically pick up on a new prerelease. I tested it on my own workstation, and it works as expected.

**Review by OlafHaag — CHANGES_REQUESTED** [review]
Thanks for contributing. I made some changes. Now I'm failing at some basics in github regarding the pull request. I want to cherry pick and only merge the update.ps1 changes, because merging the other files as well would make the appveyor update process assume the package was already updated when comparing the remote and nuspec versions.
Could you reverse the changes to any file other than the update.ps1, please?

**Comment by Gootjes** [comment]
That makes a lot of sense (it happened when I tested update.ps1 I guess). Of course! It should be fine now.

**Comment by OlafHaag** [comment]
> 
> 
> That makes a lot of sense (it happened when I tested update.ps1 I guess). Of course! It should be fine now.

You can use the WhatIf feature of AU to test what will happen without overriding these files. An output will get saved to a temporary location.

**Comment by OlafHaag** [comment]
So when I was running the update locally I got #15 , but thought it was because of the local run. Unfortunately that also happened in the appveyor build. It'll trigger `New version is available but it already exists in the Chocolatey community feed` on the next run. This isn't urgent, but should be fixed. Maybe I introduced this bug, don't know.

**Pull request merged**
